### ISSUE TITLE
Fails if repositories need authentication

### ISSUE THREAD

**Issue by alesub** [pantheon-systems/terminus-clu-plugin#15]
Our sites have a set of packages that need authentication to be installed (premium wordpress plugins). On normal CircleCI workflows we add a step to authenticate and it works fine, but in this case, the command `terminus project:clu` seems to create a separate, temporary space where this authentication is not available. Is there a way to add a hook or something similar to run the authentication within the `terminus project:clu` command?

Here's how the workflow looks in the CircleCI file:

```
  composer_lock_updater:
    <<: *defaults
    steps:
      - checkout

      - run:
          # Set TERMINUS_ENV and related environment variables.
          # https://github.com/pantheon-systems/docker-build-tools-ci/blob/6.x/scripts/set-environment
          name: setup-environment-vars
          command: /build-tools-ci/scripts/set-environment

      - run:
          name: add plugins repo authentication
          command: composer config http-basic.xxx.com $PLUGINS_KEY some_user_name

      - run:
          name: Authenticate with Terminus
          command: terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

      - run:
          name: run composer lock updater
          command: set -e && terminus project:clu $TERMINUS_SITE
```

**Comment by aaronbauman** [comment]
How does your authentication work in other workflows?
inline http-basic or auth.json should work in the composer_lock_updater
task, just like it works in any other task.
Perhaps you haven't provided the right context in your workflow definition?

**Comment by alesub** [comment]
@aaronbauman I'm adding the authentication in the exact same way in other workflows that run correctly. Here's a sample of a workflow that works:

```
build_php:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-cache-{{ checksum "composer.lock" }}
            - composer-cache-
            - vendor-{{ checksum "composer.lock" }}
            - vendor-

      - run:
          # Set TERMINUS_ENV and related environment variables.
          # https://github.com/pantheon-systems/docker-build-tools-ci/blob/6.x/scripts/set-environment
          name: setup-environment-vars
          command: /build-tools-ci/scripts/set-environment

      - run:
          name: add repo authentication
          command: composer config http-basic.xxx.com $PLUGINS_KEY some_user_name

      - run:
          name: run PHP build step
          command: ./.ci/build/php

      - save_cache:
          key: vendor-{{ checksum "composer.lock" }}
          paths:
            - $CIRCLE_WORKING_DIRECTORY/vendor

      - persist_to_workspace:
          root: .
          paths:
            - web
            - vendor
```
